<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_detail_report_app_description'] = 'Детальный отчет по сети показывает информацию о пакете и его размере.';
$lang['network_detail_report_app_name'] = 'Детальный отчет по сети';
$lang['network_detail_report_network_accounting_server'] = 'Отчетность сети сервера';
