<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_detail_report_app_description'] = 'Szczegółowy raport sieci dostarcza informacje o wielkości i pakietach.';
$lang['network_detail_report_app_name'] = 'Szczegółowy raport sieci';
$lang['network_detail_report_network_accounting_server'] = 'Sieciowy serwer rejestrujący';
